version: '3'
services:
  postgres:
    image: postgres:17.2
    container_name: fj4me
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fj4me-nest-js-api
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
      FRONTEND_URL: ${FRONTEND_URL}
      DOMAIN: ${DOMAIN}
      CORS_ORIGIN: ${CORS_ORIGIN}
      SSL: ${SSL}
      THROTTLER_LIMIT_SECONDS: ${THROTTLER_LIMIT_SECONDS}
      THROTTLER_LIMIT_QUERIES: ${THROTTLER_LIMIT_QUERIES}
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: